[server]
maxUploadSize = 200
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#00FF41"
backgroundColor = "#111111"
secondaryBackgroundColor = "#0E1117"
textColor = "#FFFFFF"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastRerenderOnChanges = true
enforceSerializableSessionState = false

[ui]
scrollToSelectedContent = true
