# La clé doit commencer par "sk-" (et non "sk-proj-")
OPENAI_API_KEY = "sk-proj-vm5ocUE8qQkVp0a-G4EfbymtzWRDKvIfujU6QQ01z98-t-qElnGjhtFOVlCL-UwGdDSauqPLqoT3BlbkFJ8k0VLkjl_Hta6SsuQD4Nh7BC8g61mXfyyEVwF1xEgJmlAfdkMveY1l20_AVknMcSxO3mB4dCIAi"
